{"uuid": "c9527dd7-905e-43e4-8d67-28a7ae2d88ba", "children": ["b28b7aa7-19c7-470a-9a3f-afcbb3058ede"], "befores": [{"name": "open_url", "status": "passed", "start": 1565948259562, "stop": 1565948260071}], "afters": [{"name": "open_url::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"/usr/local/lib/python3.7/site-packages/allure_commons/_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/_pytest/fixtures.py\", line 791, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/linguowei/PycharmProjects/spj_pytest/cases/conftest.py\", line 35, in open_url\n    driver.delete_all_cookies()\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 878, in delete_all_cookies\n    self.execute(Command.DELETE_ALL_COOKIES)\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1565948264034, "stop": 1565948264037}], "start": 1565948259562, "stop": 1565948264037}